STANDARD_MODEL_LABELS = {
    "ChatGPT5": "ChatGPT-5",
    "ChatGPT-5": "ChatGPT-5",
    "Gemini3 Pro": "Gemini 3 Pro",
    "Gemini3Pro": "Gemini 3 Pro",
    "Gemini 3 Pro": "Gemini 3 Pro",
    "ClaudeSonnet4.5": "Claude Sonnet 4.5",
    "ClaudeSonnet 4.5": "Claude Sonnet 4.5",
    "Claude Sonnet 4.5": "Claude Sonnet 4.5",
    "ChatGPT5.2": "ChatGPT-5.2",
    "ChatGPT 5.2": "ChatGPT-5.2",
    "ChatGPT-5.2": "ChatGPT-5.2",
    "Claude Sonnet 3.5": "Claude Sonnet 3.5",
    "Gemini2.5Pro": "Gemini 2.5 Pro",
    "Gemini 2.5 Pro": "Gemini 2.5 Pro",
    "DeepSeekv3": "DeepSeek-V3",
    "DeepSeek v3": "DeepSeek-V3",
    "DeepSeek-V3": "DeepSeek-V3",
    "ChatGPT4": "ChatGPT-4",
    "ChatGPT 4": "ChatGPT-4",
    "ChatGPT-4": "ChatGPT-4",
    "ClaudeSonnet4.6": "Claude Sonnet 4.6",
    "Claude Sonnet 4.6": "Claude Sonnet 4.6",
    "DeepSeek3.2": "DeepSeek-V3.2",
    "DeepSeek 3.2": "DeepSeek-V3.2",
    "DeepSeek -V3.2": "DeepSeek-V3.2",
    "DeepSeek-V3.2": "DeepSeek-V3.2",
    "Gemini3.1Pro": "Gemini 3.1 Pro",
    "Gemini 3.1Pro": "Gemini 3.1 Pro",
    "Gemini 3.1 Pro": "Gemini 3.1 Pro",
    "Chat5.4Thinking": "ChatGPT-5.4 Thinking",
    "Chat 5.4 Thinking": "ChatGPT-5.4 Thinking",
    "ChatGPT 5.4Thinking": "ChatGPT-5.4 Thinking",
    "ChatGPT 5.4 Thinking": "ChatGPT-5.4 Thinking",
    "ChatGPT5.4 Thinking": "ChatGPT-5.4 Thinking",
    "ChatGPT-5.4Thinking": "ChatGPT-5.4 Thinking",
    "ChatGPT-5.4 Thinking": "ChatGPT-5.4 Thinking",
    "Grok4.2": "Grok 4.2",
    "Grok 4.2": "Grok 4.2",
    "Llama4": "Llama 4",
    "Llama 4": "Llama 4",
    "ChaGPT t5.4": "ChatGPT-5.4",
    "ChaGPT-5.4": "ChatGPT-5.4",
    "Chat5.4": "ChatGPT-5.4",
    "ChatGPT 5.4": "ChatGPT-5.4",
    "ChatGPT5.4": "ChatGPT-5.4",
    "ChatGPT-5.4": "ChatGPT-5.4",
    "Llama3.3": "Llama 3.3",
    "Llama 3.3": "Llama 3.3",
    "Grok4": "Grok 4",
    "Grok 4": "Grok 4",
    "Gemma4": "Gemma 4",
    "Gemma 4": "Gemma 4",
    "GPT 5.5 Thinking": "ChatGPT-5.5 Thinking",
    "ChatGPT 5.5 Thinking": "ChatGPT-5.5 Thinking",
    "ChatGPT5.5 Thinking": "ChatGPT-5.5 Thinking",
    "ChatGPT-5.5 Thinking": "ChatGPT-5.5 Thinking",
    "Deepseek v4": "DeepSeek-V4",
    "DeepseekV4": "DeepSeek-V4",
    "DeepSeek V4": "DeepSeek-V4",
    "Deepseek-V4": "DeepSeek-V4",
    "Deepseek-V4 ": "DeepSeek-V4",
    "DeepSeek-V4": "DeepSeek-V4",
    "DeepSeek-V4 ": "DeepSeek-V4",
}


def standardize_model_label(label: str) -> str:
    return STANDARD_MODEL_LABELS.get(label, label)


def standardize_model_labels(labels):
    return [standardize_model_label(label) for label in labels]
